---
# handlers file for tomcat

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart tomcat instance
  ansible.builtin.service:
    name: "{{ instance_name }}"
    state: restarted
  when:
    - not ansible_check_mode | bool
    - tomcat_service_enabled
    - tomcat_service_allow_restart
